{"summary": "JET: 1 error", "tests": [{"type": "Error", "name": "PatienceError", "description": "CUSTOM ERROR: The function called test_timings_of_calculation exceded my patience", "line": 23, "variables": {"elapsed": 1.0050132500182372, "test_function": "test_timings_of_calculation"}, "out": "", "test": {"name": "Timings of calculation", "doc": "The function should not exeed 0.5 seconds.", "module": {"name": "Custom failing conditions", "doc": "Example of how to add new custom failing conditions.\nThis module shows how to add a custom error condition to your tests.\nFor example a maximum running time.\n", "path": "/Users/antonio/Documents/Projects/JET_JetTesting/tests/test_custom_failing_conditions.py", "module": null}, "routine": null}}]}