{"summary": "JET: 5 pass, 2 failed, 2 error, 1 warning", "tests": [{"type": "Error", "name": "ZeroDivisionError", "description": "division by zero", "line": 29, "variables": {}, "out": "", "test": {"name": "Division by zero product", "doc": "Division by zero should work in this algebra", "module": {"name": "Array operations", "doc": "Module to test if array operations perform as intended", "path": "/Users/antonio/Documents/Projects/JET_JetTesting/tests/test_array_operations.py", "module": null}, "routine": null}}, {"type": "Failed", "name": "AssertionError", "description": "This test did not work at all.", "line": 45, "variables": {"a": ["banana", "apple", "yellow"], "b": ["banana", "tomato", "blue", "wheel"]}, "out": "This is a print function inside the test.\nThe output is captured at runtime and stored if the test does not pass.\n", "test": {"name": "Linear sum", "doc": "This function adds two different arrays. Arrays are assumed to be of size 3", "module": {"name": "Array operations", "doc": "Module to test if array operations perform as intended", "path": "/Users/antonio/Documents/Projects/JET_JetTesting/tests/test_array_operations.py", "module": null}, "routine": null}}, {"type": "Warning", "name": "Warning", "description": "This test raised a warning", "line": 35, "variables": {}, "out": "", "test": {"name": "Scalar multiplication", "doc": "This other weird test also passed", "module": {"name": "Array operations", "doc": "Module to test if array operations perform as intended", "path": "/Users/antonio/Documents/Projects/JET_JetTesting/tests/test_array_operations.py", "module": null}, "routine": null}}, {"type": "Failed", "name": "AssertionError", "description": "Error message is displayed if test fails", "line": 21, "variables": {}, "out": "", "test": {"name": "Simple test fail", "doc": "Simple test fail", "module": {"name": "Verbose levels", "doc": "Examples of how JET displays test names.\nThese functions should all pass and show what is written when they don't.\n", "path": "/Users/antonio/Documents/Projects/JET_JetTesting/tests/test_verbose_levels.py", "module": null}, "routine": null}}, {"type": "Error", "name": "PatienceError", "description": "CUSTOM ERROR: The function called test_timings_of_calculation exceded my patience", "line": 23, "variables": {"elapsed": 1.000745083001675, "test_function": "test_timings_of_calculation"}, "out": "", "test": {"name": "Timings of calculation", "doc": "The function should not exeed 0.5 seconds.", "module": {"name": "Custom failing conditions", "doc": "Example of how to add new custom failing conditions.\nThis module shows how to add a custom error condition to your tests.\nFor example a maximum running time.\n", "path": "/Users/antonio/Documents/Projects/JET_JetTesting/tests/test_custom_failing_conditions.py", "module": null}, "routine": null}}]}